server:
  port: 8081
spring:
  rabbitmq:
    host: 10.77.0.23
    port: 5672
    username: admin
    password: admin
  listener:
    simple:
      acknowledge-mode: manual
      prefetch: 1
    direct:
      prefetch: 30
      # DataSource Config
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.0.241:1433;databaseName=trade
    username: trade
    password: Hengyi@123
#  datasource:
#    dynamic:
#      primary: master
#      strict: false
#      datasource:
#        sqlserver:
#          url: jdbc:sqlserver://192.168.0.241:1433;databaseName=trade
#          username: trade
#          password: Hengyi@123
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
logging:
  config: classpath:logback-spring.xml
